export const AppFonts = {
    MONTSERRAT_BLACK: 'montserrat_black',
    MONTSERRAT_BLACK_ITALIC: 'montserrat_black_italic',
    MONTSERRAT_BOLD: 'montserrat_bold',
    MONTSERRAT_BOLD_ITALIC: 'montserrat_bold_italic',
    MONTSERRAT_EXTRA_BOLD: 'montserrat_extra_bold',
    MONTSERRAT_EXTRA_BOLD_ITALIC: 'montserrat_extra_bold_italic',
    MONTSERRAT_EXTRA_LIGHT: 'montserrat_extra_light',
    MONTSERRAT_EXTRA_LIGHT_ITALIC: 'montserrat_extra_light_italic',
    MONTSERRAT_ITALIC: 'montserrat_italic',
    MONTSERRAT_LIGHT: 'montserrat_light',
    MONTSERRAT_LIGHT_ITALIC: 'montserrat_light_italic',
    MONTSERRAT_MEDIUM: 'montserrat_medium',
    MONTSERRAT_MEDIUM_ITALIC: 'montserrat_medium_italic',
    MONTSERRAT_REGULAR: 'montserrat_regular',
    MONTSERRAT_SEMI_BOLD: 'montserrat_semi_bold',
    MONTSERRAT_SEMI_BOLD_ITALIC: 'montserrat_semi_bold_italic',
    MONTSERRAT_THIN: 'montserrat_thin',
    MONTSERRAT_THIN_ITALIC: 'montserrat_thin_italic',
}